### PR TITLE
ENCHANCED ATOWU IN PYTHON

### PR DESCRIPTION
**Pull request by mansuf**
Added MORE Features in ATOWU Python

Progress : [Working in "bits" function]

### CODE REVIEW

**Comment by trollfist20** [comment]
Creating ATOWU in Python is Complicated AF

**Comment by trollfist20** [comment]
there's problem with azure pipelines, the python script won't running as well

**Comment by trollfist20** [comment]
Updated : Azure Pipelines is removed, i can test manually on my computer

**Review by mansuf — COMMENTED** [review]
Delete this

**Pull request closed without merging**
